packages:
  - packages/assist
  - packages/assist/frontend
  - packages/send
  - packages/send/backend
  - packages/send/frontend
  - packages/send/e2e
  - packages/shared
  - packages/addon

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  '@trpc/server@>=11.0.0 <11.8.0': '>=11.8.0'
  diff@<4.0.4: '>=4.0.4'
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  happy-dom@<20.0.0: '>=20.0.0'
  happy-dom@<20.0.2: '>=20.0.2'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
  min-document@<=2.19.0: '>=2.19.1'
  playwright@<1.55.1: '>=1.55.1'
  preact@>=10.26.5 <10.26.10: '>=10.26.10'
  qs@<6.14.1: '>=6.14.1'
  tar@<=7.5.2: '>=7.5.3'
  tmp@<=0.2.3: '>=0.2.4'
  validator@<13.15.20: '>=13.15.20'
  validator@<13.15.22: '>=13.15.22'
