packages:
  - packages/assist
  - packages/assist/frontend
  - packages/send
  - packages/send/backend
  - packages/send/frontend
  - packages/shared
  - packages/addon

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@intlify/core-base@>=10.0.0 <10.0.8': '>=10.0.8'
  brace-expansion@>=1.0.0 <=1.1.11: '>=1.1.12'
  brace-expansion@>=2.0.0 <=2.0.1: '>=2.0.2'
  esbuild@<=0.24.2: '>=0.25.0'
  formidable@>=3.1.1-canary.20211030 <3.5.3: '>=3.5.3'
  tmp@<=0.2.3: '>=0.2.4'
  vite@<=5.4.19: '>=5.4.20'
  vite@>=6.0.0 <=6.3.5: '>=6.3.6'
  vite@>=6.3.0 <=6.3.3: '>=6.3.4'
  vue-i18n@>=10.0.0 <10.0.8: '>=10.0.8'
  vue-i18n@>=11.0.0 <11.1.10: '>=11.1.10'
