packages:
  - packages/assist
  - packages/assist/frontend
  - packages/send
  - packages/send/backend
  - packages/send/frontend
  - packages/shared
  - packages/addon

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  esbuild@<=0.24.2: '>=0.25.0'
  happy-dom@<20.0.0: '>=20.0.0'
  happy-dom@<20.0.2: '>=20.0.2'
  playwright@<1.55.1: '>=1.55.1'
  tmp@<=0.2.3: '>=0.2.4'
