packages:
  - packages/assist
  - packages/assist/frontend
  - packages/send
  - packages/send/backend
  - packages/send/frontend
  - packages/send/e2e
  - packages/shared
  - packages/addon

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  '@isaacs/brace-expansion@<=5.0.0': '>=5.0.1'
  '@smithy/config-resolver@<4.4.0': '>=4.4.0'
  '@trpc/server@>=11.0.0 <11.8.0': '>=11.8.0'
  ajv@<6.14.0: '>=6.14.0'
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  axios@>=1.0.0 <=1.13.4: '>=1.13.5'
  diff@<4.0.4: '>=4.0.4'
  esbuild@<=0.24.2: '>=0.25.0'
  fast-xml-parser@>=4.1.3 <5.3.5: '>=5.3.5'
  fast-xml-parser@>=4.1.3 <5.3.6: '>=5.3.6'
  glob@>=10.2.0 <10.5.0: '>=10.5.0'
  happy-dom@<20.0.0: '>=20.0.0'
  happy-dom@<20.0.2: '>=20.0.2'
  js-yaml@<3.14.2: '>=3.14.2'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  jws@<3.2.3: '>=3.2.3'
  lodash@>=4.0.0 <=4.17.22: '>=4.17.23'
  min-document@<=2.19.0: '>=2.19.1'
  minimatch@<10.2.1: '>=10.2.1'
  playwright@<1.55.1: '>=1.55.1'
  preact@>=10.26.5 <10.26.10: '>=10.26.10'
  qs@<6.14.1: '>=6.14.1'
  qs@>=6.7.0 <=6.14.1: '>=6.14.2'
  tar@<7.5.7: '>=7.5.7'
  tar@<7.5.8: '>=7.5.8'
  tar@<=7.5.2: '>=7.5.3'
  tmp@<=0.2.3: '>=0.2.4'
  validator@<13.15.20: '>=13.15.20'
  validator@<13.15.22: '>=13.15.22'
