---
# This defines the ci environment. The ci environment is not to be considered stable, as it is used
# to test validity of changes to Pulumi code and as a breakable/fixable ci environment.

resources:
  domains:
    backend: lockbox-ci.thunderbird.dev
    frontend: send-ci.thunderbird.dev

  tb:network:MultiCidrVpc:
    vpc:
      cidr_block: 10.32.0.0/16 # Very roomy total of 65,536 available IPs
      subnets:
        # Split into two subnets with exactly half the IPs (32,768) each
        us-east-1a:
          - 10.32.0.0/17
        us-east-1b:
          - 10.32.128.0/17
      egress_via_internet_gateway: True
      enable_dns_hostnames: True
      enable_internet_gateway: True
      endpoint_interfaces:
        - ecr.api
        - ecr.dkr
        - logs
        - secretsmanager
        - ssm
      endpoint_gateways:
        - s3

  tb:network:SecurityGroupWithRules:
    backend-lb:
      rules:
        ingress:
          - cidr_blocks: ["0.0.0.0/0"]
            description: TLS port for the load balancer
            protocol: tcp
            from_port: 443
            to_port: 443
        egress:
          - cidr_blocks: ["0.0.0.0/0"]
            description: Outbound traffic
            protocol: tcp
            from_port: 0
            to_port: 65535
    backend-container:
      rules:
        ingress:
          - description: Private backend port
            protocol: tcp
            from_port: 8080
            to_port: 8080
        egress:
          - cidr_blocks: ["0.0.0.0/0"]
            description: Outbound traffic
            protocol: tcp
            from_port: 0
            to_port: 65535

  tb:secrets:PulumiSecretsManager:
    pulumi:
      secret_names:
        - b2-application-key-id
        - b2-application-key
        - database-url
        - jwt-access-token-secret
        - jwt-refresh-token-secret
        - fxa-allow-list
        - fxa-client-id
        - fxa-client-secret
        - posthog-api-key
        - sentry-auth-token
      recovery_window_in_days: 0

  tb:rds:RdsDatabaseGroup:
    citest:
      skip_final_snapshot: True
      build_jumphost: False
      jumphost_public_key: ""
      jumphost_source_cidrs: []
      secret_recovery_window_in_days: 0

  tb:fargate:FargateClusterWithLogging:
    backend:
      assign_public_ip: True
      desired_count: 1
      ecr_resources:
        - arn:aws:ecr:us-east-1:768512802988:repository/send*
      health_check_grace_period_seconds: 60
      internal: False
      services:
        send-suite:
          listener_port: 443
          listener_proto: HTTPS
          listener_cert_arn: arn:aws:acm:us-east-1:768512802988:certificate/8550cfab-84e2-432d-b9b6-a5454bacfd8c
          container_port: 8080
          container_name: backend
          # "name" field is arbitrary, but must be unique and no longer than 32 chars
          name: send-suite-ci-api
          health_check:
            healthy_threshold: 2
            unhealthy_threshold: 5
            interval: 15
      task_definition:
        network_mode: awsvpc
        # Adjust sizing as necessary; 256 cpu/512 ram are minimum values. Values must match listings in the table here:
        # https://docs.aws.amazon.com/AmazonECS/latest/cieloperguide/task_definition_parameters.html#task_size
        cpu: 512
        memory: 1024
        requires_compatibilities:
          - FARGATE
        container_definitions:
          backend:
            image: 768512802988.dkr.ecr.us-east-1.amazonaws.com/send:d9d212cf94a4135175da1e795c75e2addc66e07f
            portMappings:
              - name: send-suite
                containerPort: 8080
                hostPort: 8080
                protocol: tcp
                appProtocol: http
              - name: prisma
                containerPort: 5555
                hostPort: 5555
                protocol: tcp
                appProtocol: http
            linuxParameters:
              initProcessEnabled: True
            secrets:
              - name: B2_APPLICATION_KEY
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/b2-application-key-W8anDq
              - name: B2_APPLICATION_KEY_ID
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/b2-application-key-id-2XaCVn
              - name: DATABASE_URL
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/database-url-Bjb0pI
              - name: FXA_ALLOW_LIST
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/fxa-allow-list-DQf2Xp
              - name: FXA_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/fxa-client-id-3Vpjlh
              - name: FXA_CLIENT_SECRET
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/fxa-client-secret-i5Z47w
              - name: POSTHOG_API_KEY
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/posthog-api-key-QSay4K
              - name: SENTRY_AUTH_TOKEN
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/sentry-auth-token-H2d0hi
              - name: ACCESS_TOKEN_SECRET
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/jwt-access-token-secret-8S81TY
              - name: REFRESH_TOKEN_SECRET
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/ci/jwt-refresh-token-secret-FDUqZm
            environment:
              - name: B2_BUCKET_NAME
                value: tb-send-suite-ci-object-store
              - name: B2_ENDPOINT
                value: https://s3.us-east-005.backblazeb2.com
              - name: B2_REGION
                value: auto
              - name: BASE_URL
                value: https://lockbox-ci.thunderbird.dev/
              - name: COMBINED_LOG
                value: logs/combined.log
              - name: DEVELOPER_TIMEZONE
                value: US/Eastern
              - name: DATABASE_ENGINE
                value: postgres
              - name: DATABASE_USER
                value: sendapp
              - name: FS_LOCAL_BUCKET
                value: send-fs-local
              - name: FXA_ENTRYPOINT
                value: tblockbox
              - name: FXA_METRICS_FLOW_URL
                value: https://accounts.stage.mozaws.net/metrics-flow
              - name: FXA_MOZ_ISSUER
                value: https://accounts.stage.mozaws.net
              - name: FXA_REDIRECT_URI
                value: https://lockbox-ci.thunderbird.dev/lockbox/fxa
              - name: NODE_ENV
                value: dev
              - name: POSTHOG_HOST
                value: https://us.i.posthog.com
              - name: SEND_BACKEND_CORS_ORIGINS
                VALUE: https://send-ci.thunderbird.dev
              - name: SENTRY_DSN
                value: https://85b7b08be94b8991ed121578d807f755@o4505428107853824.ingest.us.sentry.io/4507567071232000
              - name: SENTRY_ORG
                value: thunderbird
              - name: SENTRY_PROJECT
                value: send-suite-backend
              - name: STORAGE_BACKEND
                value: b2

  tb:cloudfront:CloudFrontS3Service:
    frontend:
      forcibly_destroy_buckets: True
      service_bucket_name: tb-send-suite-ci-frontend
      certificate_arn: arn:aws:acm:us-east-1:768512802988:certificate/e3fe04b9-a8e8-4881-b5bc-257c11e17941
      distribution:
        aliases:
          - send-ci.thunderbird.dev
        comment: send-suite ci frontend
        logging_config:
          include_cookies: True

  tb:cloudwatch:CloudWatchMonitoringGroup:
    alarms: {}
    notify_emails:
      - rjung+cloudwatch@thunderbird.net
    # alarms:
    #   send-suite-ci-fargate-fargateservicealb-alb-send-suite:
    #     target_5xx:
    #       threshold: 1000
