---
resources:
  domains:
    backend: send-backend-stage.tb.pro
    frontend: send-stage.tb.pro

  tb:network:MultiCidrVpc:
    vpc:
      cidr_block: 10.31.0.0/16
      subnets:
        us-east-1a:
          - 10.31.0.0/17
        us-east-1b:
          - 10.31.128.0/17
      egress_via_internet_gateway: True
      enable_dns_hostnames: True
      enable_internet_gateway: True
      endpoint_interfaces:
        - ecr.api
        - ecr.dkr
        - logs
        - secretsmanager
        - ssm
      endpoint_gateways:
        - s3

  tb:network:SecurityGroupWithRules:
    backend-lb:
      rules:
        ingress:
          - cidr_blocks: ["0.0.0.0/0"]
            description: TLS port for the load balancer
            protocol: tcp
            from_port: 443
            to_port: 443
        egress:
          - cidr_blocks: ["0.0.0.0/0"]
            description: Outbound traffic
            protocol: tcp
            from_port: 0
            to_port: 65535
    backend-container:
      rules:
        ingress:
          - description: Private backend port
            protocol: tcp
            from_port: 8080
            to_port: 8080
        egress:
          - cidr_blocks: ["0.0.0.0/0"]
            description: Outbound traffic
            protocol: tcp
            from_port: 0
            to_port: 65535

  tb:secrets:PulumiSecretsManager:
    pulumi:
      recovery_window_in_days: 0
      secret_names:
        - b2-application-key-id
        - b2-application-key
        - database-url
        - fxa-allow-list
        - fxa-client-id
        - fxa-client-secret
        - jwt-access-token-secret
        - jwt-refresh-token-secret
        - posthog-api-key
        - sentry-auth-token

  tb:fargate:FargateClusterWithLogging:
    backend:
      desired_count: 1
      assign_public_ip: True
      ecr_resources:
        - arn:aws:ecr:us-east-1:768512802988:repository/send*
      health_check_grace_period_seconds: 60
      internal: False
      services:
        send-suite:
          listener_port: 443
          listener_proto: HTTPS
          listener_cert_arn: arn:aws:acm:us-east-1:768512802988:certificate/10824889-81a4-44d8-b34a-f47d67e5c0c8
          container_port: 8080
          container_name: backend
          # "name" field is arbitrary, but must be unique and no longer than 32 chars
          name: send-suite-stage-api
          health_check:
            healthy_threshold: 2
            unhealthy_threshold: 5
            interval: 30
      task_definition:
        network_mode: awsvpc
        cpu: 1024
        memory: 4096
        requires_compatibilities:
          - FARGATE
        container_definitions:
          backend:
            image: 768512802988.dkr.ecr.us-east-1.amazonaws.com/send:bce6bf3ffea89bb75e61e91c546551f67ab457f8
            portMappings:
              - name: send-suite
                containerPort: 8080
                hostPort: 8080
                protocol: tcp
                appProtocol: http
              - name: prisma
                containerPort: 5555
                hostPort: 5555
                protocol: tcp
                appProtocol: http
            linuxParameters:
              initProcessEnabled: True
            secrets:
              - name: B2_APPLICATION_KEY
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/b2-application-key-kiZKik
              - name: B2_APPLICATION_KEY_ID
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/b2-application-key-id-safviQ
              - name: DATABASE_URL
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/database-url-NQNiWw
              - name: FXA_ALLOW_LIST
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/fxa-allow-list-3E2Nq6
              - name: FXA_CLIENT_ID
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/fxa-client-id-rOfd3E
              - name: FXA_CLIENT_SECRET
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/fxa-client-secret-LH2cAZ
              - name: POSTHOG_API_KEY
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/posthog-api-key-Lk5pT9
              - name: SENTRY_AUTH_TOKEN
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/sentry-auth-token-a1LR5x
              - name: ACCESS_TOKEN_SECRET
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/jwt-access-token-secret-Ez9Epl
              - name: REFRESH_TOKEN_SECRET
                valueFrom: arn:aws:secretsmanager:us-east-1:768512802988:secret:send-suite/stage/jwt-refresh-token-secret-CPuCOH
            environment:
              - name: B2_BUCKET_NAME
                value: tb-send-suite-stage-object-store
              - name: B2_ENDPOINT
                value: https://s3.us-east-005.backblazeb2.com
              - name: B2_REGION
                value: auto
              - name: BASE_URL
                value: https://send-backend-stage.tb.pro/
              - name: COMBINED_LOG
                value: logs/combined.log
              - name: DEVELOPER_TIMEZONE
                value: US/Eastern
              - name: DATABASE_ENGINE
                value: postgres
              - name: DATABASE_USER
                value: sendapp
              - name: FS_LOCAL_BUCKET
                value: send-fs-local
              - name: FXA_ENTRYPOINT
                value: tblockbox
              - name: FXA_METRICS_FLOW_URL
                value: https://accounts.stage.mozaws.net/metrics-flow
              - name: FXA_MOZ_ISSUER
                value: https://accounts.stage.mozaws.net
              - name: FXA_REDIRECT_URI
                value: https://send-backend-stage.tb.pro/lockbox/fxa
              - name: NODE_ENV
                value: production
              - name: POSTHOG_HOST
                value: https://us.i.posthog.com
              - name: SEND_BACKEND_CORS_ORIGINS
                value: https://send-stage.tb.pro
              - name: SENTRY_DSN
                value: https://85b7b08be94b8991ed121578d807f755@o4505428107853824.ingest.us.sentry.io/4507567071232000
              - name: SENTRY_ORG
                value: thunderbird
              - name: SENTRY_PROJECT
                value: send-suite-backend
              - name: STORAGE_BACKEND
                value: b2

  tb:cloudfront:CloudFrontS3Service:
    frontend:
      service_bucket_name: tb-send-suite-stage-frontend
      certificate_arn: arn:aws:acm:us-east-1:768512802988:certificate/97666a05-2eb2-47cc-b1c2-22a1f3efbe31
      distribution:
        aliases:
          - send-stage.tb.pro
        comment: send-suite stage frontend
        logging_config:
          include_cookies: True

  tb:cloudwatch:CloudWatchMonitoringGroup:
    alarms: {}
    notify_emails:
      - rjung+cloudwatch@thunderbird.net
    # alarms:
    #   send-suite-stage-fargate-service:
    #     cpu_utilization:
    #       enabled: False
    #       threshold: 80

  tb:ci:AwsAutomationUser:
    ci:
      additional_policies:
        - arn:aws:iam::768512802988:policy/send-suite-ci-frontend-cache-invalidation
        - arn:aws:iam::768512802988:policy/send-suite-stage-frontend-cache-invalidation
        - arn:aws:iam::768512802988:policy/send-suite-prod-frontend-cache-invalidation
      enable_ecr_image_push: true
      ecr_repositories:
        - send
      enable_fargate_deployments: true
      fargate_clusters:
        - send-suite-ci-fargate
        - send-suite-stage-fargate
        - send-suite-prod-fargate
      fargate_task_role_arns:
        - arn:aws:iam::768512802988:role/send-suite-ci-fargate
        - arn:aws:iam::768512802988:role/send-suite-stage-fargate
        - arn:aws:iam::768512802988:role/send-suite-prod-fargate
      enable_full_s3_access: true
      s3_full_access_buckets:
        - tb-send-suite-pulumi
      enable_s3_bucket_upload: true
      s3_upload_buckets:
        - tb-send-suite-ci-frontend
        - tb-send-suite-stage-frontend
        - tb-send-suite-prod-frontend
