[project]
name = "send-suite-pulumi"
version = "0.0.2"
description = "Pulumi-built infrastructure for send-suite"
requires-python = ">=3.12"
dynamic = ["dependencies"]

[project.urls]
repository = "https://github.com/thunderbird/send-suite.git"
issues = "https://github.com/thunderbird/send-suite/issues?q=is%3Aopen+is%3Aissue+label%3Apulumi"

[tool.setuptools.dynamic]
dependencies = { file = ["requirements.txt"] }

[project.optional-dependencies]
dev = [
    "ruff"
]