# Two build arguments are possible, development and production.
# We use these to add contitional build differences.
ARG BUILD_ENV=production

FROM node:22.14.0 AS base

WORKDIR /app

# ADD every file from the top directory but no directories
ADD package.json \ 
    pnpm-lock.yaml \
    pnpm-workspace.yaml \
    nx.json \
    lerna.json \
    ./

# ADD the send-frontend directory
ADD packages/send/frontend ./packages/send/frontend
ADD packages/shared ./packages/shared

# Install dependencies 
RUN npm install -g pnpm
RUN pnpm install

# runtime production
FROM base AS runtime_production
# Set environment variable for runtime container user name
ENV runtime_user=frontend
# Add runtime user
ONBUILD RUN echo "Add runtime user"

# Add runtime user
RUN useradd ${runtime_user} -d /home/${runtime_user}
# Chown /app to runtime_user
RUN chown -Rf ${runtime_user} /app
# Switch to runtime user
USER ${runtime_user}

# runtime development
FROM base AS runtime_development
ONBUILD RUN echo "Don't add runtime user"

FROM runtime_${BUILD_ENV}
ENV CI=true

# Run the development server
CMD ["sh", "-c", "pnpm install && pnpm --filter send-frontend run dev"]
