<script lang="ts" setup>
import useApiStore from '@send-frontend/stores/api-store';

import { trpc } from '@send-frontend/lib/trpc';
import { storeToRefs } from 'pinia';
import { ref, watch } from 'vue';
import { useRoute } from 'vue-router';
import { useVerificationStore } from '../stores/verification-store';

const { api } = useApiStore();
const verificationStore = useVerificationStore();
const OTPFromRoute = useRoute().query.code as string | undefined;

const { isDeviceAskingForVerification } = storeToRefs(verificationStore);

const { handleSuccessfulVerificationForExistingClient } = verificationStore;

const codeVerification = ref<string | null>(null);
const isError = ref(false);

watch(codeVerification, (newval) => {
  if (newval.length >= 5) {
    isDeviceAskingForVerification.value = false;
  }
});

const subscriptionHandlerVerifyCode = async (data: { code: string }) => {
  console.log('running subscriptionHandlerVerifyCode with data:', data);
  if (!data || !data.code) {
    console.error('Verification failed: no code provided');
    return;
  }
  codeVerification.value = data.code;
  const { id } = await handleSuccessfulVerificationForExistingClient(data.code);
  console.log('subscriptionHandlerVerifyCode Verification successful, ID:', id);
};

trpc.onVerificationFinished.subscribe(
  { code: 'step 2 verification' },
  {
    onData: subscriptionHandlerVerifyCode,
    onStopped() {
      console.log('⛔️ Verification finished subscription stopped');
    },
    onError(err) {
      console.error('❌ Verification finished subscription error:', err);
    },
    onStarted() {
      console.log('▶️ Verification finished subscription started');
    },
  }
);

if (OTPFromRoute) {
  console.log('Code from route:', OTPFromRoute);
  await handleVerify(OTPFromRoute);
}

async function handleVerify(OTP: string) {
  if (OTP.length === 6) {
    try {
      const response = await api.call(
        'verify',
        {
          code: OTP,
        },
        'POST'
      );

      console.log('Verification successful', response);
      if (!response) {
        isError.value = true;
      }
    } catch {
      isError.value = true;
    }
  }
}

const handleCodeInput = async (event: Event) => {
  const input = event.target as HTMLInputElement;
  const code = input.value.trim().replace(/\D/g, ''); // Remove non-digits
  isError.value = false;
  // Update input value to only show digits
  input.value = code;
  await handleVerify(code);
};
</script>

<template>
  <div v-if="isDeviceAskingForVerification">
    <h1>A new device is asking for verification</h1>
    <p>
      Please enter the 6-digit verification code generated by your new device
    </p>
    <input
      type="text"
      placeholder="Enter 6-digit verification code"
      maxlength="6"
      pattern="[0-9]{6}"
      style="
        font-family: monospace;
        font-size: 24px;
        text-align: center;
        letter-spacing: 2px;
      "
      @input="handleCodeInput"
    />
    <p v-if="codeVerification">
      New device verified. Reference ID: <strong>{{ codeVerification }}</strong>
    </p>
    <p v-if="isError" style="color: red">
      Verification failed. Please try again.
    </p>
  </div>
</template>
