BUILD_PATH=$(pwd)/backend/build
echo $BUILD_PATH
rm -rf $BUILD_PATH
# Build for prod
pnpm --filter send-backend --prod deploy backend/build
# Copy the lockfile generated by pnpm deploy back to the backend directory.
# This makes it available as the Docker build context for compose.ci.yml (BUILD_ENV=production).
cp backend/build/pnpm-lock.yaml backend/pnpm-lock.yaml