# Run the nightly E2E tests on desktop browser on prod using BrowserStack; prod uses Backblaze for backend storage
name: nightly-tests-desktop-firefox

concurrency:
  group: e2e-desktop-nightly-firefox
  cancel-in-progress: true

on:
  schedule:
    # run every day at 2am UTC
    - cron:  '0 2 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  packages: read
  contents: read    # This is required for actions/checkout

jobs:
  desktop-nightly-firefox:
    name: prod-desktop-nightly-firefox
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/cached-devcontainer:latest
    environment:
      name: production
      deployment: false
    env:
      TBPRO_USERNAME: ${{ secrets.E2E_NIGHTLY_PROD_TBPRO_USERNAME }}
      TBPRO_PASSWORD: ${{ secrets.E2E_NIGHTLY_PROD_TBPRO_PASSWORD }}
      TB_SEND_ENCRYPTION_KEY_CODE: ${{ secrets.E2E_NIGHTLY_PROD_TB_SEND_ENCRYPTION_KEY_CODE }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          cd ./packages/send/e2e
          npm install

      - name: BrowserStack Env Setup
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          project-name: 'Thunderbird Send'
          build-name: 'TB Send Nightly E2E Tests (Desktop Firefox): BUILD_INFO'

      - name: Prod E2E Tests on Desktop Firefox
        # don't send GHA failure email if any of the E2E tests fail, can be annoying (check the jobs each day in BrowserStack)
        continue-on-error: true
        run: |
          cd ./packages/send/e2e
          cp .env.prod.sample .env
          npm run test:e2e:nightly:prod:browserstack:desktop:firefox
