---
name: test-fetch

on:
  push:
    branches: ['**']

permissions:
  packages: read
  contents: read

jobs:
  deploy-addon-prod-atn:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/${{ github.repository }}/cached-devcontainer:latest
    env:
      IS_CI_AUTOMATION: "yes"
    steps:
      - name: Find addon XPI asset
        id: find-addon
        if: contains(join(github.event.release.assets.*.name, ','), 'tbpro-addon-prod-')
        run: |
          name=$(jq -r '.release.assets[] | select(.name | test("tbpro-addon-prod-.*\\.xpi")) | .name' "$GITHUB_EVENT_PATH" | head -n1 || true)
          echo "xpi_name=$name" >> $GITHUB_OUTPUT

      - name: Check out the code
        if: steps.find-addon.outputs.xpi_name != ''
        uses: actions/checkout@v4

      - name: Download XPI artifact
        id: xpi-download
        if: steps.find-addon.outputs.xpi_name != ''
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          version: ${{ github.event.release.id }}
          file: ${{ steps.find-addon.outputs.xpi_name }}

      - name: ls dir
        run: ls -la