---
name: validate-workflows

concurrency:
  group: validate-workflows-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "**"
      - "!main"
    paths:
      - ".github/workflows/**"

permissions:
  contents: read

jobs:
  actionlint:
    runs-on: ubuntu-latest
    deployment: false
    steps:
      - uses: actions/checkout@v4

      - name: Run actionlint
        uses: raven-actions/actionlint@v2
